# Generated by Django 3.0.3 on 2020-04-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='apis.Driver'),
        ),
    ]
