# Generated by Django 3.0.3 on 2020-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20200424_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
